import fs from 'fs';
import path from 'path';
import { runGeneration } from './generate';
import { makeDecision } from './decision';
import { runReport } from './report';
import { runDecisionCheck } from './decision-check';
import crypto from 'crypto';

function getAllFiles(dirPath: string, arrayOfFiles: string[] = []) {
  if (!fs.existsSync(dirPath)) return arrayOfFiles;
  const files = fs.readdirSync(dirPath);
  files.forEach((file) => {
    const fullPath = path.join(dirPath, file);
    if (fs.statSync(fullPath).isDirectory()) {
      arrayOfFiles = getAllFiles(fullPath, arrayOfFiles);
    } else {
      arrayOfFiles.push(fullPath);
    }
  });
  return arrayOfFiles;
}

export function testDeterminism(baseDir: string) {
  const tmpA = '/tmp/mf-dia-loi-r2b-run-a';
  const tmpB = '/tmp/mf-dia-loi-r2b-run-b';

  if (fs.existsSync(tmpA)) fs.rmSync(tmpA, { recursive: true, force: true });
  if (fs.existsSync(tmpB)) fs.rmSync(tmpB, { recursive: true, force: true });

  const setupDir = (tmpDir: string) => {
    fs.mkdirSync(tmpDir, { recursive: true });
    fs.cpSync(path.join(baseDir, 'discovery'), path.join(tmpDir, 'discovery'), { recursive: true });
    if (fs.existsSync(path.join(baseDir, 'config'))) {
      fs.cpSync(path.join(baseDir, 'config'), path.join(tmpDir, 'config'), { recursive: true });
    }
    // We expect the normalized intake to already be generated by the `ingest` step which runs earlier.
    // It resides in `.tmp/major-fortune-dia-loi-r2b/normalized-intake.json`.
    // Actually, `generate.ts` reads from `.tmp/major-fortune-dia-loi-r2b/normalized-intake.json` via absolute path.
    // Since it's absolute, both A and B will naturally read the exact same snapshot.
  };

  setupDir(tmpA);
  setupDir(tmpB);

  // Run pipeline for A
  runGeneration(tmpA, { privateDir: tmpA, tmpDir: tmpA });
  makeDecision(tmpA);
  runReport(tmpA, { privateDir: tmpA, tmpDir: tmpA });
  runDecisionCheck(tmpA);

  // Run pipeline for B
  runGeneration(tmpB, { privateDir: tmpB, tmpDir: tmpB });
  makeDecision(tmpB);
  runReport(tmpB, { privateDir: tmpB, tmpDir: tmpB });
  runDecisionCheck(tmpB);

  // Compare A and B
  const getRelativeFiles = (dir: string) => {
    const files = getAllFiles(dir);
    return files.map(f => path.relative(dir, f)).sort();
  };

  const filesA = getRelativeFiles(tmpA);
  const filesB = getRelativeFiles(tmpB);

  const inventoryMismatches = [];
  const byteMismatches = [];
  const hashMismatches = [];

  const allFiles = new Set([...filesA, ...filesB]);
  for (const f of allFiles) {
    if (!filesA.includes(f) || !filesB.includes(f)) {
      inventoryMismatches.push(f);
      continue;
    }
    const pathA = path.join(tmpA, f);
    const pathB = path.join(tmpB, f);
    const statA = fs.statSync(pathA);
    const statB = fs.statSync(pathB);
    if (statA.size !== statB.size) {
      byteMismatches.push(f);
    }
    const bufA = fs.readFileSync(pathA);
    const bufB = fs.readFileSync(pathB);
    const hashA = crypto.createHash('sha256').update(bufA).digest('hex');
    const hashB = crypto.createHash('sha256').update(bufB).digest('hex');
    if (hashA !== hashB) {
      hashMismatches.push(f);
    }
  }

  const loadJson = (dir: string, f: string) => {
    const p = path.join(dir, f);
    if (!fs.existsSync(p)) return null;
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  };

  const obsA = loadJson(tmpA, 'obligations/obligation-evaluation-registry.json') || [];
  const obsB = loadJson(tmpB, 'obligations/obligation-evaluation-registry.json') || [];
  const obligationMismatch = JSON.stringify(obsA) !== JSON.stringify(obsB);

  const authA = loadJson(tmpA, 'authorization/dia-loi-admission-authorization.json') || [];
  const authB = loadJson(tmpB, 'authorization/dia-loi-admission-authorization.json') || [];
  const authorizationMismatch = JSON.stringify(authA) !== JSON.stringify(authB);

  const decA = loadJson(tmpA, 'reports/decision.json') || {};
  const decB = loadJson(tmpB, 'reports/decision.json') || {};
  const decisionMismatch = JSON.stringify(decA) !== JSON.stringify(decB);

  const isDeterministic = inventoryMismatches.length === 0 && byteMismatches.length === 0 && hashMismatches.length === 0 && !obligationMismatch && !authorizationMismatch && !decisionMismatch;

  const result = {
    status: isDeterministic ? 'deterministic' : 'non-deterministic',
    inventoryMismatches,
    byteMismatches,
    hashMismatches,
    obligationMismatch,
    authorizationMismatch,
    decisionMismatch
  };

  fs.mkdirSync(path.join(baseDir, 'reports'), { recursive: true });
  fs.writeFileSync(path.join(baseDir, 'reports/determinism-report.json'), JSON.stringify(result, null, 2) + '\n');

  if (!isDeterministic) {
    throw new Error(`Determinism test failed: ${JSON.stringify(result, null, 2)}`);
  }

  console.log('Determinism check passed. Both isolated runs produced byte-identical output.');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const baseDir = path.resolve(process.cwd(), 'research/major-fortune/v0.5-source-acquisition-r2b-dia-loi');
  testDeterminism(baseDir);
}
