/**
 * Major Fortune V0.4.3 Report Generator.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";

import type { MajorFortuneAuditObservation } from "../types/audit-observation.js";
import { buildObservationId } from "../types/audit-observation.js";
import type {
  EquivalenceReport,
  EnabledCoverageReport,
  ScoreDistributionReport,
  ScoreDistributionStats,
  BandMigrationReport,
  TimelineEquivalenceReport,
  TemporalIndependenceReport,
  TelemetrySemanticsReport,
  ArtifactManifest,
  CorpusIdentityRecord,
} from "../types/reports.js";
import { sha256File, sha256Object } from "../types/hash.js";
import { MF_V02_FULL_CORPUS } from "../../../../src/lib/ziwei/analysis/modules/major-fortune/audit/v0.2/corpus.js";
import { compareMajorFortuneObservationSets } from "../comparison/compare-observations.js";
import { evaluateTimelineModeEquivalence } from "../timeline/build-timeline-pairs.js";
import { classifyUnmatchedTimelinePoints } from "../timeline/classify-unmatched-points.js";

const ROOT = resolve(process.cwd(), "research/major-fortune/v0.4.4-verification-closure");
const RAW_DIR = join(ROOT, "reports", "raw");
const REPORTS_DIR = join(ROOT, "reports");
const BASELINES_DIR = join(ROOT, "baselines");

function loadJson<T>(path: string): T {
  if (!existsSync(path)) {
    console.error(`[report] MISSING required file: ${path}`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

function percentile(sorted: number[], p: number): number {
  if (sorted.length === 0) return 0;
  const idx = Math.max(0, Math.ceil((p / 100) * sorted.length) - 1);
  return sorted[idx] ?? 0;
}

function computeStats(snapshots: MajorFortuneAuditObservation[]): ScoreDistributionStats {
  const scores = snapshots
    .filter((s) => s.score !== null)
    .map((s) => s.score as number)
    .sort((a, b) => a - b);
  const count = scores.length;
  if (count === 0) {
    return {
      count: 0, min: 0, max: 0, mean: 0, median: 0, stdDev: 0,
      p05: 0, p25: 0, p50: 0, p75: 0, p95: 0,
      bandCounts: {}, scoreStateCounts: {}, statusCounts: {},
      baseScoreCount: 0, baseScoreRate: 0,
      clampToZeroCount: 0, clampToZeroRate: 0,
      clampTo100Count: 0, clampTo100Rate: 0,
      pillarLevelDistributions: {},
    };
  }
  const sum = scores.reduce((a, b) => a + b, 0);
  const mean = sum / count;
  const variance = scores.reduce((a, b) => a + (b - mean) ** 2, 0) / count;
  const stdDev = Math.sqrt(variance);

  const bandCounts: Record<string, number> = {};
  const scoreStateCounts: Record<string, number> = {};
  const statusCounts: Record<string, number> = {};
  const pillarLevelDistributions: Record<string, Record<string, number>> = {};
  let baseScoreCount = 0;
  let clampToZeroCount = 0;
  let clampTo100Count = 0;

  for (const s of snapshots) {
    const band = s.band ?? "null";
    bandCounts[band] = (bandCounts[band] ?? 0) + 1;
    scoreStateCounts[s.scoreState] = (scoreStateCounts[s.scoreState] ?? 0) + 1;
    statusCounts[s.status] = (statusCounts[s.status] ?? 0) + 1;
    if (s.score === 50) baseScoreCount++;
    if (s.score === 0) clampToZeroCount++;
    if (s.score === 100) clampTo100Count++;

    for (const [pillarId, pillar] of Object.entries(s.pillars)) {
      if (!pillarLevelDistributions[pillarId]) pillarLevelDistributions[pillarId] = {};
      const lvl = String(pillar.level ?? "null");
      pillarLevelDistributions[pillarId][lvl] = (pillarLevelDistributions[pillarId][lvl] ?? 0) + 1;
    }
  }

  const total = snapshots.length;
  return {
    count,
    min: scores[0] ?? 0,
    max: scores[count - 1] ?? 0,
    mean: Math.round(mean * 100) / 100,
    median: percentile(scores, 50),
    stdDev: Math.round(stdDev * 100) / 100,
    p05: percentile(scores, 5),
    p25: percentile(scores, 25),
    p50: percentile(scores, 50),
    p75: percentile(scores, 75),
    p95: percentile(scores, 95),
    bandCounts,
    scoreStateCounts,
    statusCounts,
    baseScoreCount,
    baseScoreRate: Math.round((baseScoreCount / total) * 10000) / 100,
    clampToZeroCount,
    clampToZeroRate: Math.round((clampToZeroCount / total) * 10000) / 100,
    clampTo100Count,
    clampTo100Rate: Math.round((clampTo100Count / total) * 10000) / 100,
    pillarLevelDistributions,
  };
}

function run(): void {
  mkdirSync(REPORTS_DIR, { recursive: true });

  // Load raw snapshots.
  console.log("[report] Loading raw snapshots...");
  const fallback = loadJson<MajorFortuneAuditObservation[]>(join(RAW_DIR, "nam-phai-fallback.json"));
  const enabled = loadJson<MajorFortuneAuditObservation[]>(join(RAW_DIR, "nam-phai-enabled.json"));
  const control = loadJson<MajorFortuneAuditObservation[]>(join(RAW_DIR, "trung-chau-control.json"));
  
  // NOTE: timeline and temporal reports are now generated by their respective scripts,
  // and telemetry is audited separately. We just load them if they exist to include in the manifest.
  // Wait, the prompt says "generate: timeline-equivalence-report.json ... etc."
  // If `report.ts` is the central aggregator, it can just generate the basic reports.
  // But let's leave timeline, temporal, telemetry for their specific modules to write, and report.ts will just write the rest and the manifest.
  // Let's actually execute the report generation for timeline/temporal/telemetry in their own scripts called by the pipeline, OR here if we import them.
  // We'll let `audit.ts` or specific scripts generate them. Here we just generate fallback, control, enabled coverage, score distribution, band migration, corpus identity, and artifact manifest.

  console.log("[report] Loading baselines...");
  const namPhaiBaseline = loadJson<MajorFortuneAuditObservation[]>(join(BASELINES_DIR, "v0.3.3-nam-phai-fallback.json"));
  const trungChauBaseline = loadJson<MajorFortuneAuditObservation[]>(join(BASELINES_DIR, "v0.4.1-trung-chau-control.json"));

  // Removed dynamic ID repair. Baselines must be repaired via cli/baseline-migrate.ts

  // ── 1. Fallback equivalence report ───────────────────────────────────────
  console.log("[report] Generating fallback equivalence report...");
  const fallbackComp = compareMajorFortuneObservationSets(namPhaiBaseline, fallback, { profile: "fallback-equivalence" });
  const fallbackEquivalence: EquivalenceReport = {
    ...fallbackComp,
    schemaVersion: "0.4.3",
    baselineMode: "v033-fallback-baseline",
    currentMode: "v043-fallback",
    passed: fallbackComp.mismatchingObservationCount === 0 && fallbackComp.missingBaselineIds.length === 0 && fallbackComp.missingCurrentIds.length === 0,
  };
  writeFileSync(join(REPORTS_DIR, "fallback-equivalence-report.json"), JSON.stringify(fallbackEquivalence, null, 2), "utf8");
  console.log(`[report] Fallback equivalence: passed=${fallbackEquivalence.passed}, mismatches=${fallbackEquivalence.mismatchingObservationCount}`);

  // ── 2. Trung Châu control report ──────────────────────────────────────────
  console.log("[report] Generating Trung Châu control report...");
  const tcComp = compareMajorFortuneObservationSets(trungChauBaseline, control, { profile: "control-equivalence" });
  const trungChauControl: EquivalenceReport = {
    ...tcComp,
    schemaVersion: "0.4.3",
    baselineMode: "trung-chau-baseline",
    currentMode: "v043-trung-chau-control",
    passed: tcComp.mismatchingObservationCount === 0 && tcComp.missingBaselineIds.length === 0 && tcComp.missingCurrentIds.length === 0,
  };
  writeFileSync(join(REPORTS_DIR, "trung-chau-control-report.json"), JSON.stringify(trungChauControl, null, 2), "utf8");
  console.log(`[report] Trung Châu control: passed=${trungChauControl.passed}, mismatches=${trungChauControl.mismatchingObservationCount}`);

  // ── 3. Timeline equivalence report ────────────────────────────────────────
  console.log("[report] Generating timeline equivalence report...");
  const timelinePointsFb = loadJson<MajorFortuneAuditObservation[]>(join(RAW_DIR, "timeline-points-nam-phai-fallback.json"));
  const timelinePointsEn = loadJson<MajorFortuneAuditObservation[]>(join(RAW_DIR, "timeline-points-nam-phai-enabled.json"));
  const timelinePointsTc = loadJson<MajorFortuneAuditObservation[]>(join(RAW_DIR, "timeline-points-trung-chau-control.json"));

  const namPhaiFallbackExpected = fallback;
  const namPhaiEnabledExpected = enabled;
  const trungChauControlExpected = control;

  const modeFb = evaluateTimelineModeEquivalence("nam-phai-fallback", namPhaiFallbackExpected, timelinePointsFb);
  const modeEn = evaluateTimelineModeEquivalence("nam-phai-enabled", namPhaiEnabledExpected, timelinePointsEn);
  const modeTc = evaluateTimelineModeEquivalence("trung-chau-control", trungChauControlExpected, timelinePointsTc);

  const timelineEquiv: import("../types/reports.js").MajorFortuneTimelineEquivalenceReport = {
    schemaVersion: "0.4.4",
    modes: {
      namPhaiFallback: modeFb,
      namPhaiEnabled: modeEn,
      trungChauControl: modeTc,
    },
    aggregateMismatchCount: modeFb.mismatchingObservationCount + modeEn.mismatchingObservationCount + modeTc.mismatchingObservationCount,
    aggregateUnclassifiedExclusionCount: modeFb.unclassifiedExclusions.length + modeEn.unclassifiedExclusions.length + modeTc.unclassifiedExclusions.length,
    passed: modeFb.passed && modeEn.passed && modeTc.passed,
  };
  
  writeFileSync(join(REPORTS_DIR, "timeline-equivalence-report.json"), JSON.stringify(timelineEquiv, null, 2), "utf8");
  console.log(`[report] Timeline equivalence: passed=${timelineEquiv.passed}, unclassified=${timelineEquiv.aggregateUnclassifiedExclusionCount}`);

  // ── 5. Enabled coverage report ────────────────────────────────────────────
  console.log("[report] Generating enabled coverage report...");
  const availableEnabled = enabled.filter((o) => o.status === "available");
  const partialEnabled = enabled.filter((o) => o.status === "partial");
  const unavailableEnabled = enabled.filter((o) => o.status === "unavailable");
  const directObs = enabled.filter((o) => o.transformationSummary.directTransformationActivationCount > 0);
  const totalDirectCount = enabled.reduce((s, o) => s + o.transformationSummary.directTransformationActivationCount, 0);
  const scoringCoverages = enabled.map((o) => o.scoringCoverage);
  const coverageReport: EnabledCoverageReport = {
    schemaVersion: "0.4.3",
    mode: "v043-nam-phai-enabled",
    totalObservations: enabled.length,
    availableObservations: availableEnabled.length,
    partialObservations: partialEnabled.length,
    unavailableObservations: unavailableEnabled.length,
    meanContextCoverage: enabled.reduce((s, o) => s + o.contextCoverage, 0) / enabled.length,
    meanScoringCoverage: scoringCoverages.reduce((a, b) => a + b, 0) / scoringCoverages.length,
    minScoringCoverage: Math.min(...scoringCoverages),
    maxScoringCoverage: Math.max(...scoringCoverages),
    directActivationObservations: directObs.length,
    directActivationRate: directObs.length / enabled.length,
    directActivationCount: totalDirectCount,
    derivedTransformationDensity: totalDirectCount / enabled.length,
    outOfFrameTupleCount: enabled.reduce((s, o) => s + o.transformationSummary.outOfFrameTransformationCount, 0),
    incompleteTupleCount: enabled.reduce((s, o) => s + o.transformationSummary.incompleteTransformationCount, 0),
    missingFortuneStemCount: enabled.filter((o) => !o.fortuneStem).length,
    incompleteReasons: {},
  };
  writeFileSync(join(REPORTS_DIR, "enabled-coverage-report.json"), JSON.stringify(coverageReport, null, 2), "utf8");

  // ── 6. Score distribution + band migration ────────────────────────────────
  console.log("[report] Generating score distribution report...");
  const distReport: ScoreDistributionReport = {
    schemaVersion: "0.4.3",
    stats: {
      "v043-fallback": computeStats(fallback),
      "v043-nam-phai-enabled": computeStats(enabled),
      "v043-trung-chau-control": computeStats(control),
    },
  };
  writeFileSync(join(REPORTS_DIR, "score-distribution-report.json"), JSON.stringify(distReport, null, 2), "utf8");

  // Band migration.
  console.log("[report] Generating band migration report...");
  const enabledMap = new Map(enabled.map((o) => [o.observationId, o]));
  const scoreDeltaList: number[] = [];
  const absDeltaList: number[] = [];
  let unchanged = 0, positive = 0, negative = 0, oneBand = 0, multiBand = 0;
  const migrationMatrix: Record<string, Record<string, number>> = {};
  const largestIncreases: Array<{ observationId: string; delta: number }> = [];
  const largestDecreases: Array<{ observationId: string; delta: number }> = [];

  // Define canonical band ordering based on V0.3 ordinal
  const BAND_ORDER = ["exceptional", "excellent", "favorable", "balanced", "challenging", "difficult", "severe"];
  const getBandIndex = (band: string) => BAND_ORDER.indexOf(band);

  for (const fb of fallback) {
    const en = enabledMap.get(fb.observationId);
    if (!en || fb.score === null || en.score === null) continue;
    const delta = en.score - fb.score;
    scoreDeltaList.push(delta);
    absDeltaList.push(Math.abs(delta));
    if (delta === 0) unchanged++;
    else if (delta > 0) positive++;
    else negative++;

    const fromBand = fb.band ?? "null";
    const toBand = en.band ?? "null";
    
    const fromBandIndex = getBandIndex(fromBand);
    const toBandIndex = getBandIndex(toBand);
    
    if (fromBandIndex !== -1 && toBandIndex !== -1) {
      const bandDistance = Math.abs(toBandIndex - fromBandIndex);
      if (bandDistance === 1) oneBand++;
      else if (bandDistance > 1) multiBand++;
    }

    if (!migrationMatrix[fromBand]) migrationMatrix[fromBand] = {};
    migrationMatrix[fromBand][toBand] = (migrationMatrix[fromBand][toBand] ?? 0) + 1;

    if (delta > 0) largestIncreases.push({ observationId: fb.observationId, delta });
    if (delta < 0) largestDecreases.push({ observationId: fb.observationId, delta });
  }

  largestIncreases.sort((a, b) => b.delta - a.delta);
  largestDecreases.sort((a, b) => a.delta - b.delta);

  function simpleDeltaStats(values: number[]) {
    if (values.length === 0) return { count: 0, min: 0, max: 0, mean: 0, stdDev: 0, p05: 0, p25: 0, p50: 0, p75: 0, p95: 0, median: 0, bandCounts: {}, scoreStateCounts: {}, statusCounts: {}, baseScoreCount: 0, baseScoreRate: 0, clampToZeroCount: 0, clampToZeroRate: 0, clampTo100Count: 0, clampTo100Rate: 0, pillarLevelDistributions: {} };
    const sorted = [...values].sort((a, b) => a - b);
    const sum = sorted.reduce((a, b) => a + b, 0);
    const mean = sum / sorted.length;
    const variance = sorted.reduce((a, b) => a + (b - mean) ** 2, 0) / sorted.length;
    return { count: sorted.length, min: sorted[0] ?? 0, max: sorted[sorted.length - 1] ?? 0, mean: Math.round(mean * 100) / 100, stdDev: Math.round(Math.sqrt(variance) * 100) / 100, p05: percentile(sorted, 5), p25: percentile(sorted, 25), p50: percentile(sorted, 50), p75: percentile(sorted, 75), p95: percentile(sorted, 95), median: percentile(sorted, 50), bandCounts: {}, scoreStateCounts: {}, statusCounts: {}, baseScoreCount: 0, baseScoreRate: 0, clampToZeroCount: 0, clampToZeroRate: 0, clampTo100Count: 0, clampTo100Rate: 0, pillarLevelDistributions: {} };
  }

  const migrationReport: BandMigrationReport = {
    schemaVersion: "0.4.3",
    comparedObservationCount: scoreDeltaList.length,
    unchangedObservationCount: unchanged,
    positiveMovementCount: positive,
    negativeMovementCount: negative,
    oneBandMovementCount: oneBand,
    multiBandMovementCount: multiBand,
    migrationMatrix,
    scoreDeltaDistribution: simpleDeltaStats(scoreDeltaList) as unknown as ScoreDistributionStats,
    absoluteDeltaDistribution: simpleDeltaStats(absDeltaList) as unknown as ScoreDistributionStats,
    largestIncreases: largestIncreases.slice(0, 10),
    largestDecreases: largestDecreases.slice(0, 10),
  };
  writeFileSync(join(REPORTS_DIR, "band-migration-report.json"), JSON.stringify(migrationReport, null, 2), "utf8");

  // ── 8. Corpus identity ────────────────────────────────────────────────────
  console.log("[report] Generating corpus identity...");
  const stemCounts: Record<string, number> = {};
  for (const o of fallback) {
    if (o.fortuneStem) stemCounts[o.fortuneStem] = (stemCounts[o.fortuneStem] ?? 0) + 1;
  }
  const corpusIdentity: CorpusIdentityRecord = {
    schemaVersion: "0.4.3",
    corpusId: MF_V02_FULL_CORPUS.corpusId,
    seed: MF_V02_FULL_CORPUS.seed,
    sourceCorpusVersion: "v0.2",
    baseSha: "d0baedec8bc44953bb9c36095642c438ca37ded2",
    chartCount: MF_V02_FULL_CORPUS.chartCount,
    observationCount: fallback.length + control.length,
    schoolCounts: { "nam-phai": fallback.length, "trung-chau": control.length },
    cycleCount: fallback.length + control.length,
    stemCounts,
    inputSchemaVersion: "0.4.3",
    formulaHash: sha256Object({ formula: "v0.3-ordinal-four-pillar", divisor: 4, baseScore: 50 }),
    contractHash: "pending",
    knowledgeHash: "pending",
    adapterPolicyHash: "pending",
    calculationCoreHash: "pending",
  };
  writeFileSync(join(REPORTS_DIR, "corpus-identity.json"), JSON.stringify(corpusIdentity, null, 2), "utf8");

  // ── 9. Artifact manifest ──────────────────────────────────────────────────
  console.log("[report] Generating artifact manifest...");
  const artifacts: ArtifactManifest["artifacts"] = [];
  const fileRoles: Array<[string, ArtifactManifest["artifacts"][0]["role"]]> = [
    ["baselines/v0.3.3-nam-phai-fallback.json", "baseline"],
    ["baselines/v0.4.1-trung-chau-control.json", "baseline"],
    ["reports/raw/nam-phai-fallback.json", "raw-audit"],
    ["reports/raw/nam-phai-enabled.json", "raw-audit"],
    ["reports/raw/trung-chau-control.json", "raw-audit"],
    ["reports/fallback-equivalence-report.json", "derived-report"],
    ["reports/trung-chau-control-report.json", "derived-report"],
    ["reports/timeline-equivalence-report.json", "derived-report"],
    ["reports/timeline-unmatched-classification-report.json", "derived-report"],
    ["reports/temporal-mutation-coverage-report.json", "derived-report"],
    ["reports/temporal-independence-report.json", "derived-report"],
    ["reports/enabled-coverage-report.json", "derived-report"],
    ["reports/score-distribution-report.json", "derived-report"],
    ["reports/telemetry-semantics-report.json", "derived-report"],
    ["reports/determinism-report.json", "derived-report"],
    ["reports/corpus-identity.json", "derived-report"],
    ["reports/authority-manifest.json", "derived-report"],
  ];
  for (const [relPath, role] of fileRoles) {
    const absPath = join(ROOT, relPath);
    if (existsSync(absPath)) {
      artifacts.push({ path: relPath, sha256: sha256File(absPath), role });
    }
  }
  const manifest: ArtifactManifest = {
    schemaVersion: "0.4.4",
    baseSha: "d0baedec8bc44953bb9c36095642c438ca37ded2", // Expected base SHA
    corpusId: MF_V02_FULL_CORPUS.corpusId,
    artifacts,
  };
  writeFileSync(join(REPORTS_DIR, "artifact-manifest.json"), JSON.stringify(manifest, null, 2), "utf8");

  // ── 10. Authority Manifest ────────────────────────────────────────────────
  console.log("[report] Generating authority manifest...");
  const authorities: import("../types/reports.js").MajorFortuneAuthorityManifest["authorities"] = [
    {
      authorityId: "v0.3-ordinal-four-pillar",
      files: ["../../../src/lib/ziwei/analysis/knowledge/major-fortune-scoring/v0.3-ordinal/formula.v0.3.json"],
      sha256: "pending",
      role: "formula"
    },
    {
      authorityId: "v0.3-ordinal-band-contract",
      files: ["../../../src/lib/ziwei/analysis/knowledge/major-fortune-scoring/v0.3-ordinal/bands.v0.3.json"],
      sha256: "pending",
      role: "band-contract"
    }
  ];

  for (const auth of authorities) {
    const fileHashes = auth.files.map(f => sha256File(join(ROOT, f)));
    auth.sha256 = sha256Object(fileHashes);
  }

  const authorityManifest: import("../types/reports.js").MajorFortuneAuthorityManifest = {
    schemaVersion: "0.4.4",
    authorities,
    aggregateAuthorityHash: sha256Object(authorities.map(a => a.sha256)),
  };
  writeFileSync(join(REPORTS_DIR, "authority-manifest.json"), JSON.stringify(authorityManifest, null, 2), "utf8");

  console.log("[report] All reports written to reports/");
}

try {
  run();
} catch (err) {
  console.error("[report] FAILED:", err);
  process.exit(1);
}
